name: Terraform Infrastructure Setup

on:
  workflow_dispatch: 

jobs:
  terraform:
    name: Terraform apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.6' 

    # Use command: az ad sp create-for-rbac --name github-actions --role Owner --scopes /subscriptions/82923ab2-fd6b-42cd-9d50-39af93cacfe8 --sdk-auth to generate required data
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      working-directory: ./scripts/terraform
      run: terraform init

    - name: Apply Terraform
      working-directory: ./scripts/terraform
      run: terraform apply -auto-approve

    - name: Get Terraform Outputs
      id: outputs
      working-directory: ./scripts/terraform
      run: |
        echo "CONTAINER_REGISTRY=$(terraform output -raw acr_login_url | grep -v "::debug")" >> $GITHUB_ENV
        echo "REGISTRY_UN=$(terraform output -raw acr_username | grep -v "::debug")" >> $GITHUB_ENV
        echo "REGISTRY_PW=$(terraform output -raw acr_password | grep -v "::debug")" >> $GITHUB_ENV
        echo "KUBE_CONFIG=$(terraform output -raw aks_kubeconfig | grep -v "::debug")" >> $GITHUB_ENV

    - name: Install GitHub CLI
      uses: actions/setup-gh@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set Secrets with GH_TOKEN
      run: |
        gh secret set CONTAINER_REGISTRY --body "$CONTAINER_REGISTRY"
        gh secret set REGISTRY_UN --body "$REGISTRY_UN"
        gh secret set REGISTRY_PW --body "$REGISTRY_PW"
        gh secret set KUBE_CONFIG --body "$KUBE_CONFIG"
