# az ad sp create-for-rbac --name "my-github-actions-sp" --role Contributor --scopes /subscriptions/YOUR_SUBSCRIPTION_ID --sdk-auth
# az acr login --name YOUR_ACR_NAME
# az acr repository list --name YOUR_ACR_NAME --output table
# az acr repository show-tags --name YOUR_ACR_NAME --repository YOUR_IMAGE_NAME --output table
# az acr repository show --name YOUR_ACR_NAME --image YOUR_IMAGE_NAME:YOUR_TAG
# az acr repository show-manifests --name YOUR_ACR_NAME --image YOUR_IMAGE_NAME:YOUR_TAG

name: Terraform Infrastructure Setup

on:
  workflow_dispatch: 


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.6' 

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      working-directory: ./scripts/terraform
      run: terraform init

    - name: Apply Terraform
      working-directory: ./scripts/terraform
      run: terraform apply -auto-approve

    - name: Get and Save Terraform Outputs
      id: tf_outputs
      working-directory: ./scripts/terraform
      run: |
        echo "CONTAINER_REGISTRY=$(terraform output -raw container_registry_login_server)" >> $GITHUB_ENV
        echo "REGISTRY_UN=$(terraform output -raw registry_admin_username)" >> $GITHUB_ENV
        echo "REGISTRY_PW=$(terraform output -raw registry_admin_password)" >> $GITHUB_ENV
        echo "KUBE_CONFIG=$(terraform output -raw kube_config | base64)" >> $GITHUB_ENV

    
    - name: Set Secrets with GH_TOKEN
      env:
        GH_TOKEN: ${{ secrets.MY_PAT }}
      run: |
        gh secret set CONTAINER_REGISTRY --body "$CONTAINER_REGISTRY"
        gh secret set REGISTRY_UN --body "$REGISTRY_UN"
        gh secret set REGISTRY_PW --body "$REGISTRY_PW"
        gh secret set KUBE_CONFIG --body "$KUBE_CONFIG"
